server:
  port: 8082

spring:
  application:
    name: api-products
  datasource:
    url: jdbc:mysql://localhost:3306/msproducts
    username: root
    password: m@rgarida2018
  jpa:
    open-in-view: true
    hibernate.ddl-auto: update

logging:
  level:
    web: debug