server: 
   port: 8083
   
spring:
   application:
      name: api-users
   datasource:
      url: jdbc:mysql://localhost:3306/msusers
      username: root
      password: m@rgarida2018
   jpa: 
      open-in-view: true
      hibernate.ddl-auto: update
      
      
   logging:
      level:
      web: debug
